import os
import sys

from manim import config
from rich.console import Console

ORIGINAL_STDOUT = sys.stdout
ORIGINAL_STDERR = sys.stderr
ORIGINAL_PROGRESS_BAR = config.progress_bar

DEFAULT_OUTPUT_VALUE = True
DEFAULT_LINE_SPACING = 0.8
DEFAULT_CURSOR_HEIGHT = 0.35
DEFAULT_CURSOR_WIDTH = 1e-4
DEFAULT_CODE_FONT = 'Consolas'
DEFAULT_CURSOR_TO_CHAR_BUFFER = 0.07
DEFAULT_TYPE_INTERVAL = 0.15
DEFAULT_LINE_BREAK_RUN_TIME = 0.4
DEFAULT_TAB_WIDTH = 4
DEFAULT_OUTPUT_CONSOLE = Console(file=ORIGINAL_STDOUT)
DEFAULT_CURSOR_BLINK_RUN_TIME = 0.5

# ffmpeg encode tuning: auto threads, fast preset, small buffer keeps memory low
FFMPEG_THREADS = os.cpu_count() or 4
FFMPEG_PRESET = "fast"
FFMPEG_BUFSIZE = "512k"

CODE_OFFSET = 0.08
NOT_AVAILABLE_CHARACTERS = '\r\v\f'
OCCUPY_CHARACTER = '('

__all__ = [
    "ORIGINAL_STDOUT",
    "ORIGINAL_STDERR",
    "ORIGINAL_PROGRESS_BAR",
    "DEFAULT_OUTPUT_VALUE",
    "DEFAULT_LINE_SPACING",
    "DEFAULT_CURSOR_HEIGHT",
    "DEFAULT_CURSOR_WIDTH",
    "DEFAULT_CODE_FONT",
    "DEFAULT_CURSOR_TO_CHAR_BUFFER",
    "DEFAULT_TYPE_INTERVAL",
    "DEFAULT_LINE_BREAK_RUN_TIME",
    "DEFAULT_TAB_WIDTH",
    "DEFAULT_OUTPUT_CONSOLE",
    "DEFAULT_CURSOR_BLINK_RUN_TIME",
    "FFMPEG_THREADS",
    "FFMPEG_PRESET",
    "FFMPEG_BUFSIZE",
    "CODE_OFFSET",
    "NOT_AVAILABLE_CHARACTERS",
    "OCCUPY_CHARACTER"
]
